import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#0D1117] h-screen w-full ">
        <div className="px-10 py-5">
          <Navbar />
          {children}
        </div>
        <Image
          src={"/concentricellipses.svg"}
          className="w-1/2 h-1/2 absolute bottom-0 -left-40"
          alt=""
          width={100}
          height={100}
        />
      </body>
    </html>
  );
}
