# Install Coco compiler

tasks:
  - name: Install Coco compiler
    init: |
      curl -L https://cocolang.s3.ap-south-1.amazonaws.com/releases/v0.3.8/coco-0.3.8-linux-amd64.tar.gz -o coco.tar.gz
    command: |
      mkdir -p ~/.coco/bin && tar -C ~/.coco/bin -xzf coco.tar.gz
      rm coco.tar.gz  # Remove the downloaded file
  - name: Set environment variable
    command: |
      echo 'export PATH=$PATH:~/.coco/bin' >> ~/.bashrc
  - name: Source Bashrc (Optional)
    command: |
      source ~/.bashrc  # This step isn't strictly necessary, but might avoid needing to restart the terminal
  - name: Verify Coco installation
    command: |
      coco version