# Install Coco compiler

tasks:
  - name: Install Coco compiler
    init: |
      curl -L https://cocolang.s3.ap-south-1.amazonaws.com/releases/v0.3.8/coco-0.3.8-linux-amd64.tar.gz -o coco.tar.gz
      mkdir -p ~/.coco/bin && tar -C ~/.coco/bin -xzf coco.tar.gz
      rm coco.tar.gz  # Remove the downloaded file
      echo 'export PATH=$PATH:~/.coco/bin' >> ~/.bashrc
      source ~/.bashrc  # Source Bashrc to apply changes
      coco version  # Verify Coco installation
