export const data = [
  {
    pnr: "XYZ123456",
    name: "Kanishk Tiwari",
    insuranceNumber: "ABC12343",
    maxClaimable: 3000,
    premiumPaid: 300,
    sourceAirportCode: "LAX",
    sourceName: "Los Angeles, CA",
    destinationAirportCode: "NYC",
    destinationName: "New York City",
    status: "Not Started",
    departureDate: "March 7, 2024",
    departureTime: "07:00 pm",
    flightNumber: "AI-420",
    seat: "B4",
  },
  {
    pnr: "ABC675849",
    name: "Kanishk Tiwari",
    insuranceNumber: "ABC12343",
    maxClaimable: 7000,
    premiumPaid: 700,
    sourceAirportCode: "IDR",
    sourceName: "Indore, MP",
    destinationAirportCode: "BHO",
    destinationName: "Bhopal, MP",
    status: "Delayed",
    departureDate: "March 10, 2024",
    departureTime: "07:00 pm",
    flightNumber: "AI-690",
    seat: "A4",
  },
];
